# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d422491e6164de13dc0b165ac9a9bc16c7c581edcbcea61b7a893a5834818ad8f1a9786e460abf5cea85e6c15150ab6aa5153315f8f5faa47d3c11183eeee1d1

test:
  secret_key_base: c7221e0f0676a1428de0b1ef66a8aa13a78aef663ac293dc6ea3d9a31eeca37ce9f8382473d772eaed79038455b2814d2b93ccd596739bfeaefee93b06c8dc8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
